/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

public class App {

    public static void main(String[] args) {

        HashTable myTable = new HashTable();


        System.out.println(repeatedWord("\"dont leave your bag all time ...\""));
    }

    public static String repeatedWord(String sentence) {
        Map<String,String> hashMap = new HashMap<>();
        sentence = sentence.replace("," , "");
        String[] allWords = sentence.split(" ");
        for (String word : allWords) {
            word = word.toLowerCase();
            if (hashMap.containsKey(word))return word;
            else  hashMap.put(word,word);
        }
        return null;
    }
}
