/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {

    public static void main(String[] args) {
        BinaryTree newTree=new BinaryTree();
        newTree.root=new Node(4);
        newTree.root.rightChild=new Node(5);
        newTree.root.leftChild=new Node(8);
        newTree.root.rightChild.leftChild=new Node(3);
        newTree.root.rightChild.rightChild=new Node(7);
        System.out.println(newTree.inOrder(newTree.root));
        newTree.inOrder(newTree.root);
        System.out.println(newTree.preOrder(newTree.root));
       System.out.println(newTree.postOrder(newTree.root));

        Node root=new Node(6);
        BinarySearchTree binarySearchTree=new BinarySearchTree(root);
        for (int i=1;i<10;i++){
            Node new2=new Node(i);
            binarySearchTree.add(new2,binarySearchTree.root);
        }
        binarySearchTree.contain(10,binarySearchTree.root);
        binarySearchTree.contain(12,binarySearchTree.root);
        System.out.println(binarySearchTree.root.leftChild.value);
    }
}
