/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }



    public static void main(String[] args) throws Exception {
        Stack  stack = new Stack();
        System.out.println(stack.empty());
        stack.push("a");
        stack.push("b");
        stack.push("c");
        System.out.println(stack.toString());
        System.out.println(stack.empty());
        System.out.println(stack.peek());
        stack.pop();
        System.out.println(stack.peek());


        Queue queue = new Queue();
        System.out.println(queue.empty());
        queue.enqueue("a");
        queue.enqueue("b");
        queue.enqueue("c");
        System.out.println(queue.empty());
        System.out.println(queue.toString());
        System.out.println(queue.peek());
        System.out.println(queue.dequeue());
        System.out.println(queue.peek());

        System.out.println("the Pseudo code: ");

        PseudoQueue test = new PseudoQueue();
        test.enqueue(9);
        test.enqueue(8);
        test.enqueue(7);
        test.enqueue(6);
        test.enqueue(5);
        test.dequeue();
        test.enqueue(12);
        test.dequeue();
        test.dequeue();
        System.out.println(test.stack1.toString());







    }
}
