/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        LinkedList firstList = new LinkedList();
        firstList.append(1);
        firstList.append(3);
        firstList.append(5);
        LinkedList secondList = new LinkedList();
        secondList.append(2);
        secondList.append(4);
        secondList.append(6);


        LinkedList newZipList = new LinkedList();
        newZipList.head = firstList.zipLists(firstList,secondList);
        System.out.println("this is the final zipped list:  ");
        System.out.println(newZipList);


        System.out.println("this is previous work form code challenges :");
        LinkedList<Integer> linkedList = new LinkedList<Integer>();
        linkedList.insert(1);
        linkedList.insert(4);
        linkedList.insert(10);
        linkedList.insert(3);
        linkedList.insert(2);
        linkedList.insert(11);
        linkedList.insert(21);
        System.out.println( linkedList.toString());
        System.out.println( linkedList.includes(10));
        System.out.println( linkedList.includes(6));

        System.out.println(linkedList.kthFromEnd(3));

        linkedList.insertAfter(4,11);
        linkedList.insertBefore(1,15);



        System.out.println( linkedList.toString());

    }
}