/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class BinarySearchTree extends BinaryTree{
    Node root;
    public BinarySearchTree(Node root) {
        this.root=root;
    }
    public void add(Node newNode,Node rootExplore) {
        if (rootExplore == null) {
            return;
        }
        if (newNode.value > rootExplore.value) {
            if (rootExplore.rightChild == null)
                rootExplore.rightChild = newNode;
            else
                add(newNode, rootExplore.rightChild);

        }
        if (newNode.value < rootExplore.value) {
            if (rootExplore.leftChild == null)
                rootExplore.leftChild = newNode;
            else
                add(newNode, rootExplore.leftChild);
        }
    }
    public boolean contain(int num,Node rootExplore){
        if(rootExplore==null){
            try {
                throw new Exception("not found");
            } catch (Exception e) {
                e.printStackTrace();
                return false;
            }
        }
        if(rootExplore.value==num){
            System.out.println("found");
            return true;
        }
        if(num>rootExplore.value){
            contain(num,rootExplore.rightChild);

        }
        if(num<rootExplore.value){
            contain(num,rootExplore.leftChild);
        }
        return false;
    }
}